[SQUASH] Launcher3: Import bcsmartspace lib
Squash of:

Author: Daniel Jacob Chittoor <djchittoor47@gmail.com>
Date:   Thu Jul 21 01:37:15 2022 +0530

    SystemUI: Implement Reverse-engineered Smartspace

    From SQ3A.220605.009.A1

    [ghostrider-reborn]
    - Adapt to aosp, fix crash on click, misc cleanup

    Change-Id: I39444dd95621ccfbe1dfd737e357145014e440d0
    Co-authored-by: Anay Wadhera <awadhera@berkeley.edu>
    Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>

Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Thu Aug 18 19:11:14 2022 +0530

    SystemUI: Forward-port smartspace to Android 13

    Change-Id: Iddf5c22562b1858e3159fd939c54890e23b29063
    Signed-off-by: DennySPb <dennyspb@gmail.com>

Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date:   Sat Oct 15 15:04:25 2022 +0000

    SystemUI: BcSmartspaceView: Allow setting current page

    Required by launcher smartspace.

    Change-Id: I51d7728b6b2d3d7dfb06e39d1c9363f89795b54f

Author: Adithya R <gh0strider.2k18.reborn@gmail.com>
Date: Wed, 25 Jan 2023 18:24:21 +0530

    DerpLauncher: Update smartspace to 13-QPR1

    Change-Id: I129995246b696bb4834cd757b31bc9fee698a49c

Author: Ido Ben-Hur <idoybh2@gmail.com>
Date: Wed, 15 Mar 2023 11:21:00 +0200

    DerpLauncher: smartspace: Adapt to 13-QPR2

    Change-Id: I331fc8a205f425c2d50fd0adfd82b8185c03c599

Co-authored-by: DennySPb <dennyspb@gmail.com>
Co-authored-by: Anay Wadhera <awadhera@berkeley.edu>
Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Change-Id: Ib9fa2f4f3f14fa4b1a891db9dfc067f37c9bbc58

Launcher3: bcsmartspace: Import translations

Change-Id: I64d0b27559c36ac818b6d70fa096aa206ebeabb5

Launcher3: Open google weather on tapping smartspace

Since smartspace weather activity won't open due to
caller package (Launcher3) not being google signed,
hijack the intent to open the google app's exported
weather activity, which behaves in the same fashion.

Change-Id: Ic01ede73ab6253bcb301ac794985c3720c5beda3

Launcher3: Update smartspace to 14

Launcher3: Adapt Smartspace A15-QPR1

* Building error text
error: BcSmartspaceView is not abstract and does not override abstract method setBgHandler(Handler) in SmartspaceView
public class BcSmartspaceView extends FrameLayout implements BcSmartspaceDataPlugin.SmartspaceTargetListener, BcSmartspaceDataPlugin.SmartspaceView {

Signed-off-by: clarencelol <clarencekuiek@proton.me>

Launcher3: Remove top padding from smartspace date card

Matches other cards and prevents the content from being too close to
the page indicator.

Change-Id: I092055e36883095118ef281232fa3721b7c54aa7

Co-authored-by: DennySPb <dennyspb@gmail.com>
Co-authored-by: Anay Wadhera <awadhera@berkeley.edu>
Co-authored-by: Adithya R <gh0strider.2k18.reborn@gmail.com>
Co-authored-by: xyyx <xyyx@mail.ru>
Co-authored-by: clarencelol <clarencekuiek@proton.me>
Change-Id: I60ca4f553371d4899953fee696d9d0b4e8536a30